### ISSUE TITLE
shadow piercing css warnings in Chrome 45

### ISSUE THREAD

**Issue by azakus** [PolymerElements/paper-styles#73] opened 2015-11-11 19:32 UTC
_From @Jijeshp920 on September 2, 2015 14:23_

```
/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
polymer.js:10032 
Calling Element.createShadowRoot() for an element which already hosts a shadow root is deprecated. See https://www.chromestatus.com/features/4668884095336448 for more details.
jquery-1.11.3.min.js:2 
::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
'Touch.webkitRadiusX' is deprecated and will be removed in M47, around November 2015. Please use 'Touch.radiusX' instead.
'Touch.webkitRadiusY' is deprecated and will be removed in M47, around November 2015. Please use 'Touch.radiusY' instead.
'Touch.webkitForce' is deprecated and will be removed in M47, around November 2015. Please use 'Touch.force' instead.
```

_Copied from original issue: Polymer/polymer#2394_

**Comment by azakus** [comment] 2015-11-11 19:32
_From @ebidel on October 6, 2015 17:1_

Yea, multiple shadow hosts is deprecated in Chrome. What element was showing this so we can track it down?

**Comment by azakus** [comment] 2015-11-11 19:32
_From @optimisme on October 8, 2015 13:43_

iron-flex-layout/classes/iron-shadow-flex-layout.html
paper-styles/classes/shadow-layout.html

**Comment by azakus** [comment] 2015-11-11 19:32
The multiple shadowroot warning is not related to those styles. Looks like a jquery function tried to create another shadowroot in your output.

**Comment by notwaldorf** [comment] 2015-11-12 22:47
The multiple shadow roots isn't coming from `paper-styles`. The `/deep/` usage we are aware of, and is a duplicate of https://github.com/PolymerElements/paper-styles/issues/49.

**Closed by notwaldorf** 2015-11-12 22:47 UTC
