### ISSUE TITLE
/deep/ depreached

### ISSUE THREAD

**Issue by oathcomrade** [PolymerElements/paper-styles#58] opened 2015-10-03 20:13 UTC
Browser returns the following warning:
/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
/deep/ should be replaced with the current standard.

**Comment by cdata** [comment] 2015-10-05 15:59
Thanks for reporting. We are currently working on changes to minimize the impact from `/deep/` being removed. Please track https://github.com/PolymerElements/iron-flex-layout/pull/32 for the latest on this.

Closing this issue as a dupe of https://github.com/PolymerElements/iron-flex-layout/issues/37

**Closed by cdata** 2015-10-05 15:59 UTC
