### ISSUE TITLE
Use PolymerElements/font-roboto import

### ISSUE THREAD

**Issue by ebidel** [PolymerElements/paper-styles#38] opened 2015-06-16 00:19 UTC
This element should include `PolymerElements/font-roboto.html` as a dep and use that intead of the fonts.google.com URLs:

https://github.com/PolymerElements/paper-styles/blob/d23af125cb74978532c25e5cd152f9b2e6d991c8/classes/typography.html#L11

https://github.com/PolymerElements/paper-styles/blob/d23af125cb74978532c25e5cd152f9b2e6d991c8/typography.html#L11

**Comment by ebidel** [comment] 2015-06-26 13:07
@justinfagnani can we update https://github.com/PolymerElements/paper-styles/blob/master/classes/typography.html#L11 to use the import as well, and retag?

**Comment by rubenstolk** [comment] 2015-06-27 09:01
And don't we need to do the same for `Inconsolata` also?

**Comment by rubenstolk** [comment] 2015-06-27 09:06
And I wonder if we shouldn't use embedded fonts rather than google fonts. Especially in cases of e.g. Cordova icm PolymerStarterKit you wouldn't want fonts to load from Google. With this setup it is impossible to get rid of those font imports because everything depends on `paper-styles`...

**Comment by ebidel** [comment] 2015-06-27 12:07
Agreed that there should be a local option. Two issues that capture that:
https://github.com/PolymerElements/paper-styles/issues/39
https://github.com/PolymerElements/paper-styles/issues/22

**Comment by addyosmani** [comment] 2015-06-27 13:10
For the most common use-case, taking advantage of the (heavily) edge cached version of Roboto and Insonsolata from Google fonts is going to make sense. I do think we should try to figure out a way to make this setup sufficiently flexible that you could switch it up for a local copy if that was your preference (current defaults in paper-styles make that challenging).

**Comment by azakus** [comment] 2015-07-14 00:08
Fixed by #44

**Closed by azakus** 2015-07-14 00:08 UTC

**Comment by s-trooper** [comment] 2016-09-20 10:52
is there regression? i get "https://fonts.googleapis.com"  and "fonts.googleapis.com" request all time ...
