### ISSUE TITLE
Need to parameterize path to fonts

### ISSUE THREAD

**Issue by tjsavage** [PolymerElements/paper-styles#33] opened 2015-06-05 01:11 UTC
Hey,

I'm building a new app at my current employer with Apache Cordova and Polymer.  This is being built in Visual Studio 2015, with the goal of deploying it to Android, iOS, and Windows.  Exciting stuff.

Except the path to fonts isn't parameterized in the core Polymer controls, and, once installed on a mobile device, my packaged app is failing to retrieve fonts successfully (since it's trying to retrieve the fonts under file://....; not to mention it's trying to make a call over-the-wire, which I want to avoid by serving these fonts locally).  Would it be possible to parameterize the path to fonts in the polymer controls?  I'd *really* like to avoid having to diverge from the trunk on the polymer controls.

Thanks!  I'm very open to alternatives if there's a better way of solving this problem....

Ryan

**Comment by morethanreal** [comment] 2015-06-05 21:53
We need to fix this. Maybe for now we can provide an import that does not fetch the font, and have the developer load the font via some other method.

**Comment by dzhioev** [comment] 2015-06-13 00:49
+1, we have the same problem in Chromium Web UI, where protocol is "chrome://".

**Comment by notwaldorf** [comment] 2015-06-19 21:16
I think this is a duplicate of https://github.com/PolymerElements/paper-styles/issues/22

**Closed by notwaldorf** 2015-06-19 21:16 UTC
Labels: duplicate
