### ISSUE TITLE
Deprication warning in importing paper-styles

### ISSUE THREAD

**Issue by WarrenGonsalves** [PolymerElements/paper-styles#116] opened 2016-08-26 12:54 UTC
On importing "/bower_components/paper-styles/paper-styles.html" the following warnings are shown in the console : 

> This file is deprecated. Please use `iron-flex-layout/iron-flex-layout-classes.html`, and one of the specific dom-modules instead                 iron-flex-layout.html:12

and

> /deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.

This is for the latest version 1.1.4 of paper-styles

I'm guessing this is because "../iron-flex-layout/classes/iron-flex-layout.html" is being imported in paper-styles instead of "../iron-flex-layout/iron-flex-layout-classes.html"

**Comment by notwaldorf** [comment] 2016-08-26 18:15
You're right -- the warning happens because `paper-styles.html` includes all the deprecated classes as well. This cannot be deleted right now since it's a breaking change (and tracked separately in https://github.com/PolymerElements/paper-styles/issues/49). As the docs mention, you shouldn't use the aggregated `paper-styles.html`, but one of the separate imports explicitly.

Closing as this is technically a duplicate of https://github.com/PolymerElements/paper-styles/issues/49

**Closed by notwaldorf** 2016-08-26 18:15 UTC
